version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: testlab
      POSTGRES_PASSWORD: testlab
      POSTGRES_DB: testlab
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://testlab:testlab@db:5432/testlab
      JWT_SECRET: devsecret
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE=http://localhost:8000
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: {}
