[tool.black]
line-length = 100
target-version = ["py312"]
exclude = [
  "/.venv",
  "/migrations",
]

[tool.ruff]
line-length = 100
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # bugbear
  "UP", # pyupgrade
]
ignore = [
  "E203",  # black compatibility on slices
]
exclude = [
  ".venv",
  "migrations",
]

[tool.ruff.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
